on: [push, pull_request]
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix develop --command poetry run ./script.sh all-tests
        # TODO: use `nix flake check`
